nome = input('Digite seu nome completo: ').strip()
input('Analizando seu nome...')
print(f'Seu nome em maiúsculas é: {nome.upper()}')
print(f'Seu nome em minúsculas é: {nome.lower()}')
print(f'Seu nome tem {len(nome) - nome.count(" ")} letras.')
print(f'Seu primeiro nome é {nome.split()[0]} e ele tem {len(nome.split()[0])} letras.')
print(f'Seu último nome é {nome.split()[-1]} e ele tem {len(nome.split()[-1])} letras.')
